### ISSUE TITLE
Productivity Extension: Angular File Changer

### ISSUE THREAD

**Issue by jtcrowson** [loiane/angular-extension-pack-vsce#10]
Hi @loiane,

Wondering if you'd consider adding Angular File Changer in addition to or in replacement of angular2-switcher.  It has similar functionality, but also has Mac Touch Bar and NgRx support.

[Angular File Changer Marketplace Link](https://marketplace.visualstudio.com/items?itemName=john-crowson.angular-file-changer)

**Comment by loiane** [comment]
Sure, can you pls raise PR for this?

**Comment by loiane** [comment]
Extension added.
