### ISSUE TITLE
Productivity Extension: Angular-cli

### ISSUE THREAD

**Issue by SegerdeKort** [loiane/angular-extension-pack-vsce#13]
Hi @loiane,

I was wondering if you can add the Angular-cli extension?

This extensions allows you to create components, services., pipes.. from the explore menu using the angular cli. A real productivity booster in larger projects. 🚀

[Angular-cli](https://marketplace.visualstudio.com/items?itemName=segerdekort.angular-cli)

**Comment by loiane** [comment]
Extension added.
