### ISSUE TITLE
TSLint (deprecated)

### ISSUE THREAD

**Issue by abhith** [loiane/angular-extension-pack-vsce#8]
[vscode-tslint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) (deprecated)

**Note**: This extension has been deprecated in favor of the [vscode-typescript-tslint-plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin). To learn about the differences between vscode-tslint and the new extension please refer to this [document](https://github.com/Microsoft/vscode-typescript-tslint-plugin#differences-with-the-vscode-tslint-extension).

**Comment by loiane** [comment]
Thanks for opening the issue! Already fixed!
